(function(g,h,n){g.SPR||(g.SPR={provide:function(a,b){d[a]||(d[a]=b,"function"===typeof d[a].init&&d[a].init())}});var d=g.SPR;d.provide("Common",{random:function(){return Math.floor(8675309*Math.random())},isArray:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},isString:function(a){return"[object String]"===Object.prototype.toString.call(a)},hasOwnProperty:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}});d.provide("DOM",{init:function(){function a(){d.DOM.flush();
g.removeEventListener("DOMContentLoaded",a,!1)}function b(){/loaded|interactive|complete/.test(h.readyState)&&(h.detachEvent("onreadystatechange",b),c&&(c=!1,d.DOM.flush()))}d.DOM.on=d.DOM.attachEvent;d.DOM.off=d.DOM.detachEvent;var c=!0;g.addEventListener&&g.addEventListener("DOMContentLoaded",a);h.attachEvent&&h.attachEvent("onreadystatechange",b)},addIframeSync:function(a){var b=h.createElement("iframe");b.setAttribute("name","spr");b.src=a;b.setAttribute("height","1");b.setAttribute("width","1");
b.setAttribute("visible","false");b.style.display="none";h.body.appendChild(b);return b},addScript:function(a){var b=h.createElement("script");b.type="text/javascript";b.setAttribute("async",!0);b.setAttribute("name","spr");b.src=a;d.DOM.onReady(function(){setTimeout(function(){d.DOM.$("HEAD")[0].appendChild(b)},1)});return b},queue:[],ready:/loaded|interactive|complete/.test(h.readyState),flush:function(){var a=d.DOM.queue.shift();for(d.DOM.ready=!0;a;)a(),a=d.DOM.queue.shift()},onReady:function(a){d.DOM.ready?
(d.DOM.queue.push(a),d.DOM.flush()):h.documentElement.doScroll?g.self===g.top?function(){if(!h.uniqueID&&h.expando)return d.DOM.queue.push(a);try{h.documentElement.doScroll("left"),a()}catch(b){setTimeout(arguments.callee,0)}}():d.DOM.queue.push(a):d.DOM.queue.push(a)},attachEvent:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},detachEvent:function(a,b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},top:function(a){return a?
a.y?a.y:a.offsetTop+d.DOM.top(a.offsetParent):0},left:function(a){return a?a.x?a.x:a.offsetLeft+d.DOM.left(a.offsetParent):0},height:function(a){return Math.max(a.scrollHeight||0,a.offsetHeight||0,a.clientHeight||0)},width:function(a){return Math.max(a.scrollWidth||0,a.offsetWidth||0,a.clientWidth||0)},scroll:function(){var a=0;return a=g.pageYOffset?g.pageYOffset:h.documentElement?h.documentElement.scrollTop:0},viewport:function(){var a=0,b=0,b=h.documentElement;g.innerWidth?(a=g.innerWidth,b=g.innerHeight):
(b&&b.clientWidth||(b=d.$("BODY")[0]),a=b.clientWidth,b=b.clientHeight);return{w:a,h:b}},getsupportedprop:function(a){for(var b=h.documentElement,c=0;c<a.length;c++)if("string"==typeof b.style[a[c]])return a[c]},$:function(a){var b=[],c,d=0,f;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(h.getElementById(a.substring(1)));break;case ".":c=h.getElementsByTagName("*");for(f=" "+a.substring(1)+" ";d<c.length;d+=1)a=(" "+c[d].className+" ").replace(/[\n\t\r]/g," "),
-1<a.indexOf(f)&&b.push(c[d]);break;default:b=h.getElementsByTagName(a)}return b}});d.provide("QS",{escape:function(a){return encodeURIComponent(a)},unescape:function(a){return decodeURIComponent(a)},encode:function(a,b){var c=d.QS,e=[];if(d.Common.isArray(a))for(var f=0,k;f<a.length;f+=1)k=a[f],/\[\]$/.test(b)?e.push(c.escape(b)+"="+c.escape(k)):e.push(c.encode(k,b+"["+("object"===typeof k?f:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)e.push(c.escape(b)+"="+c.escape(a));else for(f in a)Object.prototype.hasOwnProperty.call(a,
f)&&(b?e.push(c.encode(a[f],b+"["+f+"]")):e.push(c.encode(a[f],f)));return e.join("&")},decode:function(a){var b={},c=0,e={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var f=a[c].split("="),k=d.QS.unescape(f[0]),l=b,m=0,g=k.split("]["),h=g.length-1;/\[/.test(g[0])&&/\]$/.test(g[h])?(g[h]=g[h].replace(/\]$/,""),g=g.shift().split("[").concat(g),h=g.length-1):h=0;if(2===f.length)if(f=(f=d.QS.unescape(f[1]))&&!isNaN(f)?+f:"undefined"===f?void 0:void 0!==e[f]?
e[f]:f,h)for(;m<=h;m+=1)k=""===g[m]?l.length:g[m],l=l[k]=m<h?l[k]||(g[m+1]&&isNaN(g[m+1])?{}:[]):f;else d.Common.isArray(b[k])?b[k].push(f):b[k]=void 0!==b[k]?[b[k],f]:f;else k&&(b[k]=void 0)}return b}});d.provide("API",{callbacks:{},jsonp:function(a,b,c,e,f){e=e||n;f||(f="cb");var k="cb"+d.Common.random(),l=d.API;c[f]="SPR.API.callbacks."+k;f=g.location.protocol+"//";"file://"===f&&(f="http://");c=d.QS.encode(c);var h=d.DOM.addScript(f+a+b+"?"+c);l.callbacks[k]=function(a){setTimeout(function(){h.parentNode.removeChild(h)},
0);e(a);try{delete l.callbacks[k]}catch(c){l.callbacks[k]=null}}}});d.provide("XD",{callbacks:{},xport:null,init:function(){d.XD.xport=g.postMessage?d.XD.PM:d.XD.Fragment;d.XD.xport.init()},send:function(a,b,c,e){e=e||{};e.__message__=c;d.XD.xport.send(a,b,d.QS.encode(e))},recv:function(a){a=d.QS.decode(a);var b=d.XD.callbacks[a.__message__],c=0;if(b)for(;c<b.length;c+=1)if("function"===typeof b[c])b[c](a)},on:function(a,b){b=b||n;d.XD.callbacks[a]=d.XD.callbacks[a]||[];d.XD.callbacks[a].push(b)},
once:function(a,b){b=b||n;d.XD.on(a,function(a){b(a);b=n})},PM:{init:function(){d.DOM.attachEvent(g,"message",function(a){d.XD.recv(a.data)})},send:function(a,b,c){a.postMessage(c,g.location.protocol+"//"+(b.host||b))}},Fragment:{init:function(){function a(){var f=g.location.hash;f!==c&&b.test(f)&&(d.XD.recv(f.replace(b,"")),g.location.hash=c);(f=e.queue.shift())&&e.setHash.apply(null,f);e.interval=setTimeout(a,e.delay)}var b,c,e=d.XD.Fragment;c=g.location.hash;b=/.*&\d{11,15}data:/;a()},delay:100,
queue:[],send:function(a){d.XD.Fragment.queue.push(arguments)},setHash:function(a,b,c){var d;d=(b.hash||"").replace(/^#+/,"");b=b.location||"";d=d+"&"+ +new Date+"data:"+c;a.location=b+"#"+d}}});d.provide("Cookie",{patterns:{},get:function(a){var b=h.cookie||"",c=d.Cookie.patterns[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),d.Cookie.patterns[a]=c);return(a=b.match(c))&&d.QS.unescape(a[1])},set:function(a,b,c){var d="";c&&(d="; expires="+
c.toGMTString());h.cookie=a+"="+b+d+"; path=/"},del:function(a){d.Cookie.set(a,"",new Date(1982,5,13))}});d.provide("FX",{init:function(){d.FX.Animation.prototype={add:function(a){for(var b,c,e=0;e<a.length;e+=1)c=a[e],b=c.fx?d.FX.Easing[c.fx]:d.FX.Easing.ease,this.queue.push(new d.FX.Tween(this.el.style,c.type,b,c.from,c.to,c.duration,"px"))},run:function(a){for(var b=0,c=this.queue,d=0,f=function(){d+=1;d===c.length&&"function"===typeof a&&a()};b<c.length;b+=1)c[b].start(f)}};d.FX.Tween.prototype=
{func:function(a,b,c,d){return c*a/d+b},setTime:function(a){this.prevTime=this._time;a>this._duration?this.looping?(this.rewind(a-this._duration),this.update()):(this._time=this._duration,this.update(),this.stop(),this.callback()):(0>a?this.rewind():this._time=a,this.update())},setPosition:function(a){var b=""!==this.suffixe?this.suffixe:"";this.prevPos=this._pos;this.obj[this.prop]=Math.round(a)+b;this._pos=a},getPosition:function(a){a||(a=this._time);return this.func(a,this.begin,this.change,this._duration)},
init:function(a,b,c,e,f,g,l){arguments.length&&(l&&(this.suffixe=l),this.callback=n,this.obj=a,this.prop=b,this.begin=e,this.finish=f,this._pos=e,this._duration=!g||0>=g?1E5:g,this.func=c||d.FX.Easing.none,this.change=f-this.begin)},start:function(a){"function"===typeof a&&(this.callback=a);this.begin||(this._pos=this.begin=parseInt(this.obj[this.prop],10),this.change=this.finish-this.begin);this.rewind();this.stop();this.isPlaying=!0;this.onEnterFrame()},rewind:function(a){this.stop();this._time=
a?a:0;this.fixTime();this.update()},update:function(){this.setPosition(this.getPosition(this._time))},onEnterFrame:function(){var a=this;a.isPlaying&&(a.nextFrame(),setTimeout(function(){a.onEnterFrame()},0))},nextFrame:function(){this.setTime((this.getTimer()-this._startTime)/1E3)},stop:function(){this.isPlaying=!1},fixTime:function(){this._startTime=this.getTimer()-1E3*this._time},getTimer:function(){return(new Date).getTime()-this._time}}},Animation:function(a,b){this.queue=[];this.el=a;this.add(b)},
Tween:function(a,b,c,d,f,g,l){this.obj={};this.prop="";this.prevPos=this.prevTime=this.change=0;this.looping=!1;this._finish=this._startTime=this._position=this._pos=this._time=this._duration=0;this.suffixe=this.name="";this.init(a,b,c,d,f,g,l)},Easing:{none:function(a,b,c,d){return c*a/d+b},ease:function(a,b,c,d){return 1>(a/=d/2)?c/2*a*a*a*a*a+b:c/2*((a-=2)*a*a*a*a+2)+b},bounce:function(a,b,c,d){var f=0.867;return 1>(a/=d/2)?c/2*a*a*(((f*=1.525)+1)*a-f)+b:c/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+b}}});
d.provide("de",{api:"feeds.delicious.com",apiPath:"/v2/json/urlinfo/data",collect:function(a){var b=d.de;d.API.jsonp(b.api,b.apiPath,{url:a.url},function(c){d.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"de",data:c})},"callback")}});d.provide("dg",{api:"services.digg.com",apiPath:"/stories/",collect:function(a){var b=d.dg;d.API.jsonp(b.api,b.apiPath,{type:"javascript",link:a.url},function(c){d.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,
pid:a.pid,sn:"dg",data:c})},"callback")}});d.provide("fb",{api:"graph.facebook.com",apiPath:"/fql",collect:function(a){var b=d.fb;d.API.jsonp(b.api,b.apiPath,{q:'SELECT url,total_count,share_count,comment_count,like_count,click_count,commentsbox_count FROM link_stat WHERE url in ("'+a.url+'")'},function(c){d.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"fb",data:c})},"callback")}});d.provide("gp",{api:"clients6.google.com",apiPath:"rpc",collect:function(a){}});
d.provide("li",{api:"www.linkedin.com",apiPath:"/countserv/count/share",collect:function(a){var b=d.li;d.API.jsonp(b.api,b.apiPath,{url:a.url},function(c){d.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"li",data:c})},"callback")}});d.provide("rd",{api:"www.reddit.com",apiPath:"/api/info.json",collect:function(a){var b=d.rd;d.API.jsonp(b.api,b.apiPath,{url:a.url},function(c){d.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"rd",
data:c})},"jsonp")}});d.provide("pi",{api:"partners-api.pinterest.com",apiPath:"/v1/urls/count.json",collect:function(a){var b=d.pi;d.API.jsonp(b.api,b.apiPath,{url:a.url},function(c){d.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"pi",data:c})},"callback")}});d.provide("su",{api:"www.stumbleupon.com",apiPath:"/services/1.01/badge.getinfo",collect:function(a){var b=d.su;d.API.jsonp(b.api,b.apiPath,{url:a.url},function(c){d.API.jsonp("cc.simplereach.com","/event",
{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"su",data:c})})}});d.provide("tw",{api:"urls.api.twitter.com",apiPath:"/1/urls/count.json",collect:function(a){var b=d.tw;d.API.jsonp(b.api,b.apiPath,{url:a.url},function(c){d.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"tw",data:c})},"callback")}});d.provide("Reach",{api:"cc.simplereach.com",cdn:"d8rk54i4mohrb.cloudfront.net",config:{},init:function(){if(g.location.host!==d.Reach.cdn)try{var a=d.Reach,b=g.__reach_config||
g.__spr_config,c=a.config||{},e;for(e in b)void 0===c[e]&&(c[e]=b[e]);c.ckw&&(c.tags=c.ckw.split(" "));c.pub&&(c.date=c.pub);c.cat&&(c.channels=c.cat.split(" "));if(!0===c.no_slide||1===c.no_slide)c.slide_active=!1;a.config=c;a.collect(c)}catch(f){d.DOM.onReady(function(){var a=h.createElement("img");a.src="http://cc.simplereach.com/pixel?bad=true&error="+f.message;a.setAttribute("width","1px");h.body.appendChild(a)})}},collect:function(a){function b(a){"string"===typeof a&&(a=a.split(","));if(d.Common.isArray(a)){for(var c=
0;c<a.length;c+=1)"string"===typeof a[c]&&(a[c]=a[c].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}return a}var c=d.Reach,e={};e.pid=a.pid;e.url=a.url;e.title=a.title;e.date=a.date;e.domain=a.domain;e.ref_url=a.ref_url;e.referrer=a.referrer||h.referrer;e.page_url=a.page_url;a.authors&&(e.authors=b(a.authors));a.channels&&(e.channels=b(a.channels));a.tags&&(e.tags=b(a.tags));a.brand_tags&&(e.brand_tags=b(a.brand_tags));a.date&&"string"!==typeof a.date&&(e.date=a.date.toString());
if(null!==e.pid&&void 0!==e.pid&&e.url&&e.date){if(0===e.url.indexOf("http%3"))try{e.url=decodeURIComponent(e.url)}catch(f){e.url=unescape(e.url)}a.url=e.url;a.iframe?(e.page_url=g.location.toString(),e.ref_url=e.ref_url||h.referrer,e.cache_buster=(new Date).getTime(),a=d.QS.encode(e),d.DOM.addIframeSync("//"+d.Reach.cdn+"/iframe.html?"+a)):(0===e.pid&&(e.pid="000000000000000000000000"),d.API.jsonp(c.api,"/n",e,function(a){if(!1!==a.slide){var b=!1;!0===c.config.slide_active?b=!0:!1!==c.config.slide_active&&
!0===a.slide&&(b=!0);d.Slide&&(!0===b&&!1===d.Slide.enabled)&&d.Slide.enable(a.id)}a.de&&d.de.collect(a);a.dg&&d.dg.collect(a);a.fb&&d.fb.collect(a);a.gp&&d.gp.collect(a);a.li&&d.li.collect(a);a.rd&&d.rd.collect(a);a.su&&d.su.collect(a);a.tw&&d.tw.collect(a);a.pi&&d.pi.collect(a)}))}else if(!a.ignore_errors)try{console.log("SPR-ERROR: Please provide pid, url and date in the configuration")}catch(k){}}});d.provide("Slide",{domain:d.Reach.cdn,api:"slide.simplereach.com",template:"/slides/slide.html?"+
d.Common.random(),cookie:"__sruid",optOutCookie:"__spr_opt_out",config:{},isHost:!0,recommendations:null,remote:null,hasOpened:!1,evtopts:{},debug:!1,enabled:!1,cid:null,fx:{},sharethrough:"b.sharethrough.com",init:function(){function a(a){d.XD.on(a,function(c){b[a](c)})}var b=d.Slide,c=d.Cookie;g.location.host!==b.domain&&b.createConfig();if(!b.config.no_slide&&"true"!==c.get(b.optOutCookie)){g.location.host===b.domain&&b.localInit();for(var c="recommend setState help setOptOut run setCookie setOptOutCookie open close slideIn toggleHelp showShares".split(" "),
e=0;e<c.length;e+=1)a(c[e])}},createConfig:function(){for(var a=g.__reach_config||g.__spr_config||{},b=d.Reach.config,c={},e="pid offset disallow_opt_out slide_logo header css uid no_slide loc bg_color_code header_color_code box_shadow_opacity".split(" "),f,h,l=e.length-1;0<=l;l--)f=e[l],h=void 0,void 0!==b[f]?h=b[f]:void 0!==a[f]?h=a[f]:"slide_logo"===f?h=!0:"uid"===f&&(h=d.Cookie.get(d.Slide.cookie)),void 0!==h&&(c[f]=h);d.Slide.config=c},enable:function(a){d.DOM.onReady(function(){d.Slide.remoteInit(a)})},
localInit:function(){var a=d.Slide,b=d.QS.decode(g.location.hash.substring(1));a.isHost=!1;a.domain=b.host;a.hash=b.hash;a.location=b.location;a.remote=g.parent},remoteInit:function(a){var b=d.DOM,c=d.Slide,e=c.config.loc,f=b.$("body")[0];"string"===typeof e&&(-1===e.indexOf("#")&&-1===e.indexOf("."))&&(e="#"+e);c.enabled=!0;c.content=b.$(e)[0]||f;c.mult=c.content===f?0.55:0.95;c.cid=a;c.recommend()},xd:function(a,b){d.XD.send(d.Slide.remote,{location:d.Slide.location,host:d.Slide.domain,hash:d.Slide.hash},
a,b)},recommend:function(a,b){var c=d.Slide,e=d.QS,f=d.DOM,k=d.XD,l=d.API;if(c.isHost)l.jsonp(c.api,"/p/n",{pid:c.config.pid,cid:c.cid},function(a){var b;if(a.hl&&0!==a.hl.length){var f=e.encode({host:g.location.host,hash:g.location.hash,location:g.location.href});b=h.location.protocol+"//"+c.domain+c.template;c.frame=c.createFrame(b+"#"+f);c.remote=c.frame.contentWindow;c.location=b;k.once("slide-init",function(b){var e={};if(c.config.offset){var f=parseInt(c.config.offset,10);"undefined"!==typeof b.start.top&&
(b.start.top=f+"px");"undefined"!==typeof b.start.bottom&&(b.start.bottom=f+"px")}c.fx=b;c.setCookie(a.uid)||(e.setCookie={uid:a.uid});a.pid=c.config.pid;c.evtopts={uid:a.uid,tid:a.tid,pid:c.config.pid,a:a.hl[0].id};d.Slide.sharethroughEvent({actionType:"impression",sessionId:c.evtopts.uid},function(){});e.recommend={res:a,config:c.config};c.xd("run",e);c.bindEvents()})}});else f.onReady(function(){var b=a.res.hl[0];c.config=a.config;c.hl=b;c.evtopts={uid:a.res.uid,tid:a.res.tid,pid:a.config.pid,
a:b.id};f.$("#simplereach-slide-link")[0].href=b.u;f.$("#simplereach-slide-link")[0].innerHTML=b.t;c.config.disallow_opt_out&&(f.$("#simplereach-slide-help-button")[0].style.display="none");!1===c.config.slide_logo?f.$("#logo")[0].style.display="none":f.$("#logo")[0].style.display="block";c.config.header&&(f.$("#simplereach-slide-title")[0].innerHTML=c.config.header);c.config.css&&(b=h.createElement("link"),b.rel="stylesheet",b.type="text/css",b.href=c.config.css,f.$("HEAD")[0].appendChild(b));c.config.bg_color_code&&
(f.$("#simplereach-slide-element")[0].style.backgroundColor=c.config.bg_color_code);c.config.header_color_code&&(f.$("#simplereach-slide-title")[0].style.color=c.config.header_color_code);c.bindEvents()})},createFrame:function(a){var b=h.createElement("iframe"),c=h.createElement("div"),e=d.DOM.getsupportedprop(["boxShadow","MozBoxShadow","WebkitBoxShadow"]);c.setAttribute("id","simplereach-slide-element");c.style.position="fixed";c.style.left=0;c.style.right=0;c.style.width="100%";c.style.height=
0;c.style.zIndex=8675309;c.style.overflow="visible";c.style.bottom=0;b.scrolling="no";b.frameBorder="0";b.src=a;b.style.position="absolute";b.style.display="none";b.style.border="none";b.style[e]="0px 0px 10px #000";d.Slide.config.box_shadow_opacity&&(b.style[e]="0px 0px 10px rgba(0,0,0,"+d.Slide.config.box_shadow_opacity+")");b.allowtransparency="true";c.appendChild(b);d.DOM.$("BODY")[0].appendChild(c);return b},bindEvents:function(){var a=d.Slide,b=d.DOM;a.isHost?(b.on(g,"scroll",a.onScroll),"true"===
d.Cookie.get(a.optOutCookie)&&(a.optedOut=!0)):(b.on(b.$("#simplereach-slide-close-button")[0],"click",function(){a.close({detach:!0})}),b.on(b.$("#simplereach-slide-open-button")[0],"click",function(){a.open()}),b.on(b.$("#simplereach-slide-help-button")[0],"click",function(){a.help()}),b.on(b.$("#simplereach-slide-link")[0],"click",function(){var c="?u="+a.hl.eu+"&"+d.QS.encode(a.evtopts);b.$("#simplereach-slide-link")[0].href=h.location.protocol+"//"+a.api+"/p/c"+c;d.Slide.sharethroughEvent({actionType:"click",
sessionId:a.evtopts.uid},function(){})}),!1!==a.config.slide_logo&&(b.$("#logo-link")[0].href="http://simplereach.com?ref="+a.domain,b.$("#logo-link-f")[0].href="http://simplereach.com?ref="+a.domain),b.on(b.$("#save")[0],"click",function(){var c=b.$("#opt-out-n")[0].checked;a.setOptOutCookie({tf:c});a.setOptOut();d.API.jsonp(a.api,c?"/p/oo":"/p/oi",a.evtopts)}),a.setOptOut())},setOptOut:function(a,b){var c=d.Slide,e=d.DOM;c.isHost?(e="true"===d.Cookie.get(c.optOutCookie),c.xd("setOptOut",{oo:e})):
a?(c.optedOut=a.oo,e.$("#opt-out-y")[0].checked=!c.optedOut,e.$("#opt-out-n")[0].checked=c.optedOut,c.close({detach:!0},function(){c.optedOut||c.open()})):c.xd("setOptOut",{})},show_fb:function(){if(-1===navigator.appVersion.indexOf("MSIE 7.")&&-1===navigator.appVersion.indexOf("MSIE 8.")){var a=d.Slide;if(!a.isHost){var b=d.DOM,c=b.$("#fb-root")[0];b.addScript(h.location.protocol+"//connect.facebook.net/en_US/all.js");c.style.display="block";c.innerHTML='<fb:like href="'+a.hl.u+'" layout="button_count" show-faces="false" action="like" colorscheme="light"></fb:like>';
g.fbAsyncInit=function(){g.FB.init({appId:"200433859985229",status:!0,cookie:!0,xfbml:!0})}}}},show_tw:function(){var a=d.Slide;if(!a.isHost){var b=d.DOM,c=b.$("#tw-root")[0],e=h.createElement("a");c.style.display="block";b.addScript(h.location.protocol+"//platform.twitter.com/widgets.js",!0);e.setAttribute("href","http://twitter.com/share");e.setAttribute("class","twitter-share-button");e.setAttribute("data-url",a.hl.su||a.hl.u);e.setAttribute("data-counturl",a.hl.u);e.setAttribute("data-text",a.hl.t);
c.appendChild(e)}},show_goog:function(){if(!d.Slide.isHost){var a=d.DOM,b=a.$("#goog-root")[0];b.style.display="block";b.innerHTML='<g:plusone size="medium" href="'+d.Slide.hl.u+'"></g:plusone>';a.addScript(h.location.protocol+"//apis.google.com/js/plusone.js",!0)}},show_img:function(){var a=d.Slide;if(!a.isHost&&a.hl.i){var b=d.DOM,c=b.$("#icon-link")[0],e=b.$("#simplereach-slide-image")[0];c.style.display="block";c.href=a.hl.u;c.alt=a.hl.t;e.src=h.location.protocol+"//"+d.Reach.cdn+a.hl.i;b.on(c,
"click",function(){var c="?u="+a.hl.eu+"&"+d.QS.encode(a.evtopts);b.$("#simplereach-slide-link")[0].href=h.location.protocol+"//"+a.api+"/p/c"+c;d.Slide.sharethroughEvent({actionType:"click",sessionId:a.evtopts.uid},function(){})})}},help:function(a){var b=d.Slide;a=d.DOM;b.isHost?b.close({detach:!0},function(){(new d.FX.Animation(b.frame,b.fx.slideHelp)).run();b.setState({state:"open",toggleHelp:{state:"visible"}})}):(a.$("#simplereach-slide-help-header")[0].innerHTML="OPTIONS FOR "+b.domain.toUpperCase(),
b.xd("help"))},onScroll:function(){var a=d.Slide,b=d.DOM,c=b.height(a.content)+b.top(a.content);b.viewport().h*a.mult+b.scroll()>c*a.mult?a.open():a.close()},showShares:function(){var a=d.Slide;if(a.isHost)a.xd("showShares");else for(var b=0;b<a.hl.st.length;b+=1)a["show_"+a.hl.st[b]]()},slideIn:function(){var a=d.Slide;if(a.isHost){if(!a.inMotion){var b,c=new d.FX.Animation(a.frame,a.fx.slideIn),e="open";a.optedOut&&(c.add(a.fx.slideClose),e="closed");a.frame.style.display="block";for(b in a.fx.start)Object.prototype.hasOwnProperty.call(a.fx.start,
b)&&(a.frame.style[b]=a.fx.start[b]);a.inMotion=!0;c.run(function(){a.inMotion=!1;a.hasShown=!0;a.setState({state:e});a.optedOut?d.DOM.off(g,"scroll",a.onScroll):(d.API.jsonp(a.api,"/p/i",a.evtopts),a.impression=!0,a.showShares(),d.Slide.sharethroughEvent({actionType:"visibleImpression",sessionId:a.evtopts.uid},function(){}))})}}else a.xd("slideIn")},open:function(a,b){var c=d.Slide;if(c.isHost)if(!c.hasShown)c.slideIn();else{if(!c.inMotion&&c.isClosed&&!c.isOpen){var e=new d.FX.Animation(c.frame,
c.fx.slideOpen);c.inMotion=!0;e.run(function(){c.inMotion=!1;c.setState({state:"open"});a&&a.detach&&d.DOM.off(g,"scroll",c.onScroll);c.impression||(d.API.jsonp(c.api,"/p/i",c.evtopts),c.impression=!0,d.Slide.sharethroughEvent({actionType:"visibleImpression",sessionId:c.evtopts.uid},function(){}));b&&b()})}}else c.xd("open")},close:function(a,b){var c=d.Slide;if(c.isHost)if(c.inMotion||c.isClosed||!c.isOpen)c.inMotion||b&&b();else{var e=new d.FX.Animation(c.frame,c.fx.slideClose);c.inMotion=!0;e.run(function(){c.inMotion=
!1;c.setState({state:"closed"});a&&a.detach&&d.DOM.off(g,"scroll",c.onScroll);b&&b()})}else c.xd("close",a)},toggleHelp:function(a){var b=d.Slide,c=d.DOM;if(b.isHost&&!a.noSend)b.xd("toggleHelp",a);else{var e=c.$("#simplereach-slide-content")[0].style,f=c.$("#simplereach-slide-help-button")[0].style,g=c.$("#simplereach-slide-footer")[0].style,h=c.$("#simplereach-slide-help")[0].style,m=c.$("#simplereach-slide-help-header")[0].style,c=c.$("#simplereach-slide-title")[0].style;"hidden"===a.state?(e.display=
"block",b.config.disallow_opt_out||(f.display="block"),h.display="none",g.display="block",m.display="none",c.display="block"):(e.display="none",f.display="none",h.display="block",g.display="none",m.display="block",c.display="none")}},setState:function(a){var b=d.Slide,c=d.DOM.$,e=a.state;b.isHost?(c={setState:{state:e}},"closed"===e?(b.isClosed=!0,b.isOpen=!1,c.toggleHelp={state:"hidden"}):"open"===e&&(b.isClosed=!1,b.isOpen=!0),a.toggleHelp&&(c.toggleHelp=a.toggleHelp),c.toggleHelp&&(c.toggleHelp.noSend=
!0),b.xd("run",c)):(a=c("#simplereach-slide-close-button")[0],b=c("#simplereach-slide-open-button")[0],"closed"===e?(a.style.display="none",b.style.display="block"):"open"===e&&(b.style.display="none",a.style.display="block"))},run:function(a){var b=d.Slide,c,e;for(e in a)d.Common.hasOwnProperty(a,e)&&(c=b[e])&&c(a[e])},setCookie:function(a){var b=d.Slide;d.Cookie.set(b.cookie,a.uid||a,new Date(2032,5,13));return!b.isHost},setOptOutCookie:function(a){var b=d.Slide,c=d.Cookie;b.isHost?a.tf?c.set(b.optOutCookie,
"true"):c.del(b.optOutCookie):b.xd("setOptOutCookie",a)},sharethroughEvent:function(a,b){d.API.jsonp(d.Slide.sharethrough,"/slide",{type:a.actionType,session:a.sessionId},function(a){b()})}})})(window,document,function(){});
