// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package demo.rmi.print.server;

public final class RemotePrinterImpl_Stub
    extends java.rmi.server.RemoteStub
    implements demo.rmi.print.common.RemotePrinter, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getPinterStatus_0;
    private static java.lang.reflect.Method $method_isCompplete_1;
    private static java.lang.reflect.Method $method_submitJob_2;
    
    static {
	try {
	    $method_getPinterStatus_0 = demo.rmi.print.common.RemotePrinter.class.getMethod("getPinterStatus", new java.lang.Class[] {});
	    $method_isCompplete_1 = demo.rmi.print.common.RemotePrinter.class.getMethod("isCompplete", new java.lang.Class[] {int.class});
	    $method_submitJob_2 = demo.rmi.print.common.RemotePrinter.class.getMethod("submitJob", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RemotePrinterImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getPinterStatus()
    public java.lang.String getPinterStatus()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getPinterStatus_0, null, 3415313673159508368L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of isCompplete(int)
    public boolean isCompplete(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_isCompplete_1, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -1220638729017066541L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of submitJob(String)
    public int submitJob(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_submitJob_2, new java.lang.Object[] {$param_String_1}, -1033171104106073084L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
